### ISSUE TITLE
license-checker (spdx) can't read license

### ISSUE THREAD

**Issue by peteruithoven** [RIAEvangelist/js-message#2]
[license-checker](https://www.npmjs.com/package/license-checker) (spdx) can't read the license of this package.

> We walk through the node_modules directory with the read-installed module. Once we gathered a list of modules we walk through them and look at all of their package.json's, We try to identify the license with the spdx module to see if it has a valid SPDX license attached. If that fails, we then look into the module for the following files: LICENSE, LICENCE, COPYING, & README.
> 
> If one of the those files are found (in that order) we will attempt to parse the license data from it with a list of known license texts. This will be shown with the * next to the name of the license to show that we "guessed" at it.

I think the easy fix is renaming `licence.md` to `LICENCE`.

You do state DBAD license in package.json, not sure why that's not used.

**Comment by peteruithoven** [comment]
I opened an issue in the license-checker: https://github.com/davglass/license-checker/issues/244.

**Comment by peteruithoven** [comment]
Relevant existing discussion: https://github.com/RIAEvangelist/node-ipc/issues/133

**Comment by RIAEvangelist** [comment]
Switched to MIT
